apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-service-app
  namespace: tinder-space
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-service-app
  template:
    metadata:
      labels:
        app: profile-service-app
    spec:
      containers:
        - name: profile-service-app
          image: testUrl/profile-service:5f015caca6dd080dd6104c292fd23c842b963149
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: profile-config
            - secretRef:
                name: tinder-secrets
